### ISSUE TITLE
Just spawn with gun

### ISSUE THREAD

**Issue by cspemb** [dawnE64/BaseBumpRepo#10]
If you pick up a gun, change the color in the pause menu, then pick up another gun, you can see the player is holding multiple guns. The player should only be holding 1 gun at a time.

**Comment by Nlarseny** [comment]
Gun will spawn as soon as player tries to shoot, for some reason it will not replicate if I try to use the Begin Event, but will if any other kind of event is triggered (currently using Launch Event). I think that it's good enough for now.
