### ISSUE TITLE
Framerate for client is slow?

### ISSUE THREAD

**Issue by dawnE64** [dawnE64/BaseBumpRepo#24]

**Comment by Nlarseny** [comment]
From doing some research it looks like this could be an UE5 issue. Many people have said 4.26 works great but the new 5 versions have given them grief with low FPS on high end computers.

**Comment by dawnE64** [comment]
That's odd. Let's talk about this with everyone during the next meeting. I personally don't want to switch to UE4 just because I like the new interface but maybe it would be worth it haha

**Comment by dawnE64** [comment]
It's actually sped up quite a bit for me. Maybe it just slows down while streaming on Discord?

**Comment by Nlarseny** [comment]
That sounds right, my computer can barely run unreal so that's probably a big factor too.
