### ISSUE TITLE
Missing Replication

### ISSUE THREAD

**Issue by Nlarseny** [dawnE64/BaseBumpRepo#3]
Looks like the replication is missing now along with collisions. The level is back to default as well. Earlier versions work, so we may need to backtrack and then add stuff in again.

**Comment by dawnE64** [comment]
- [ ] Which files are replications supposed to be happening in? The Player Controller? If we can check the last commit that changed that file it's probably where things went wrong.
- [ ] And what do you mean by the level is back to default?

**Comment by Nlarseny** [comment]
Works now
